name: Cache Test

on:
  workflow_dispatch:

jobs:
  cache-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create cache folder
        run: mkdir -p ~/.cache/demo

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/demo
          key: cache-326a757

      - name: prime-cache-326a757
        run: echo Cache hit: ${{ steps.cache.outputs.cache-hit }}
